In [11]:
import numpy as np 
import pandas as pd 
import seaborn as sns

In [12]:
df = pd.read_csv("../data/processed_data.csv")
df.head()

   cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0

In [13]:
#Step-5 Feature selection(not done here as only 2 features are there)

#Step-6 Extracting input(indepedent) and output(dependent) columns

X = df.iloc[:, 0:2] #features
y = df.iloc[:, -1] #label

In [14]:
print(X.shape, y.shape) #Here, X must be a matrix(2-d tensor), while y(label) must be a vector(1-d tensor)

(100, 2) (100,)

In [15]:
#Step-7 -- Train-test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [16]:
X_train

    cgpa     iq
18   4.0  100.0
30   7.6  128.0
73   4.9   61.0
33   6.0  149.0
90   7.3   86.0
..   ...    ...
60   6.9  139.0
71   6.1  132.0
14   6.1  103.0
92   5.2  110.0
51   4.8  141.0

[90 rows x 2 columns]

In [17]:
X_test

    cgpa     iq
83   7.5  130.0
53   8.3  168.0
70   6.3  127.0
45   6.0   66.0
44   7.5   61.0
39   4.6  146.0
22   4.9  120.0
80   4.9  196.0
10   6.0   45.0
0    6.8  123.0