In [44]:
import numpy as np 
import pandas as pd 
import seaborn as sns

In [45]:
df = pd.read_csv("../data/processed_data.csv")
df.head()

   cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0

In [46]:
#Step-5 Feature selection(not done here as only 2 features are there)

#Step-6 Extracting input(indepedent) and output(dependent) columns

X = df.iloc[:, 0:2] #features
y = df.iloc[:, -1] #label

In [47]:
print(X.shape, y.shape) #Here, X must be a matrix(2-d tensor), while y(label) must be a vector(1-d tensor)

(100, 2) (100,)

In [48]:
#Step-7 -- Train-test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [49]:
X_train

    cgpa     iq
18   4.0  100.0
30   7.6  128.0
73   4.9   61.0
33   6.0  149.0
90   7.3   86.0
..   ...    ...
60   6.9  139.0
71   6.1  132.0
14   6.1  103.0
92   5.2  110.0
51   4.8  141.0

[90 rows x 2 columns]

In [50]:
X_test

    cgpa     iq
83   7.5  130.0
53   8.3  168.0
70   6.3  127.0
45   6.0   66.0
44   7.5   61.0
39   4.6  146.0
22   4.9  120.0
80   4.9  196.0
10   6.0   45.0
0    6.8  123.0

In [51]:
#Step-8 -- Scaling the values

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [52]:
X_train

array([[-1.73718527, -0.62029848],
       [ 1.45537303,  0.09806189],
       [-0.9390457 , -1.62087186],
       [ 0.03645823,  0.63683217],
       [ 1.1893265 , -0.97947867],
       [-0.14090612,  0.45724208],
       [-0.9390457 ,  0.79076654],
       [ 1.1893265 , -1.90308486],
       [-0.49563482,  0.3802749 ],
       [-1.82586745, -0.38939693],
       [ 1.63273738, -0.26111829],
       [-1.38245657,  0.63683217],
       [ 0.92327998,  1.91961855],
       [ 1.45537303, -0.90251149],
       [ 2.2535126 , -0.10718393],
       [-0.76168135,  1.32953682],
       [-0.9390457 ,  0.25199626],
       [-1.38245657, -2.10833068],
       [-0.76168135, -1.49259322],
       [ 1.1893265 , -0.20980684],
       [ 0.8345978 ,  0.35461917],
       [-0.67299917,  0.9447009 ],
       [-0.14090612,  1.07297954],
       [-0.67299917, -0.87685576],
       [ 0.74591563, -0.31242975],
       [ 1.01196215, -1.95439632],
       [ 0.8345978 , -0.72292139],
       [ 1.8987839 ,  1.07297954],
       [ 0.74591563, -0.87685576],
       [-0.67299917,  2.56101175],
       [-0.49563482,  0.27765199],
       [-1.02772787,  0.99601236],
       [-0.85036352, -1.5695604 ],
       [-1.47113875,  1.94527428],
       [ 0.03645823, -0.00456102],
       [-0.67299917,  0.2006848 ],
       [-0.49563482, -0.44070839],
       [-0.85036352, -0.85120003],
       [ 0.03645823, -0.56898703],
       [ 0.39118693, -0.20980684],
       [-1.11641005, -0.0815282 ],
       [ 1.27800868,  0.2006848 ],
       [-2.3579605 ,  1.50912691],
       [ 0.4798691 ,  0.91904518],
       [ 0.1251404 ,  0.81642227],
       [ 0.1251404 , -1.10775731],
       [-0.2295883 ,  0.48289781],
       [ 0.92327998, -1.54390468],
       [-0.2295883 ,  0.40593062],
       [-0.9390457 ,  0.68814363],
       [ 0.1251404 , -1.51824895],
       [ 0.21382258, -0.28677402],
       [ 0.39118693,  0.43158635],
       [ 0.74591563,  0.43158635],
       [-2.18059615,  2.79191329],
       [-0.85036352, -0.15849538],
       [-0.584317  , -0.26111829],
       [-1.73718527, -1.26169167],
       [ 1.1893265 ,  0.32896344],
       [ 0.65723345,  1.48347118],
       [ 0.4798691 , -0.87685576],
       [-0.49563482, -0.26111829],
       [ 1.81010173, -1.15906876],
       [ 0.56855128,  0.35461917],
       [ 0.30250475, -0.5433313 ],
       [ 0.4798691 ,  0.14937335],
       [-1.02772787,  1.14994673],
       [ 0.92327998,  0.3802749 ],
       [-1.11641005, -1.85177341],
       [-1.02772787, -0.31242975],
       [ 0.30250475,  0.09806189],
       [-0.2295883 ,  1.14994673],
       [ 1.8987839 ,  0.63683217],
       [ 0.92327998, -0.31242975],
       [-0.05222395, -0.46636412],
       [ 0.92327998,  1.30388109],
       [ 1.01196215,  0.68814363],
       [-0.584317  , -0.0815282 ],
       [-1.11641005, -0.95382294],
       [-0.2295883 ,  0.2006848 ],
       [ 1.36669085,  0.86773372],
       [ 0.65723345,  0.76511081],
       [-0.76168135,  0.09806189],
       [ 0.4798691 , -2.23660932],
       [ 0.56855128, -0.10718393],
       [ 0.8345978 ,  0.3802749 ],
       [ 0.1251404 ,  0.2006848 ],
       [ 0.1251404 , -0.5433313 ],
       [-0.67299917, -0.36374121],
       [-1.02772787,  0.43158635]])

In [53]:
X_test

array([[ 1.36669085,  0.14937335],
       [ 2.07614825,  1.124291  ],
       [ 0.30250475,  0.07240616],
       [ 0.03645823, -1.49259322],
       [ 1.36669085, -1.62087186],
       [-1.20509222,  0.55986499],
       [-0.9390457 , -0.10718393],
       [-0.9390457 ,  1.84265137],
       [ 0.03645823, -2.0313635 ],
       [ 0.74591563, -0.03021675]])

In [54]:
#Step-9 -- Model training and testing

#Training

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [55]:
#Testing and evaluating

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_percent = accuracy_score(y_test, y_pred) * 100

print(accuracy_percent)

80.0